### ISSUE TITLE
Share the CAD files?

### ISSUE THREAD

**Issue by KeLaiFu** [TOILmodular/Tides#1]
Would it be possible to share the CAD files for this and your other mutable instruments designs? I am not sure if it's a requirement of the license with MI modules, but it seems to be very common with other MI clones that the eagle/kicad/easyeda files are included in the repositories.

thanks for sharing your work anyway and keep those entertaining youtube videos coming!

**Comment by TOILmodular** [comment]
First of all, thanks a lot for the feedback. I am working on more stuff to share.

I fear, I do not know how to create CAD files from EasyEDA or how to work with them. I do not even know much about the content of the generated Gerber files. I just took the easy straight forward way to have them generated in EasyEDA and forward them to the PCB maker.
I do not know if these zipped files are some kind of standard, or if there is any available tool to convert them to other formats.
Sorry, that I cannot help concerning that point.

**Comment by KeLaiFu** [comment]
I am not too familiar with EasyEDA, but I believe you just need to go to 'export' in the file menu and there's an EasyEDA option. The output file should be PCB_filename.json, or SCH_filename.json, depending on which view you have open at the time.

**Comment by TOILmodular** [comment]
You might try that. I think, I will not dive further into creating other formats out of the Gerber file set, since it is sufficient for having the PCBs created.
